modLoader = "javafml"
loaderVersion = "[47,48)"
license = "All Rights Reserved"
[[mods]]
modId = "optileaves"
version = "${version}"
displayName = "OptiLeaves"
displayTest = "IGNORE_ALL_VERSION"
description = '''
OptiLeaves - mod for leaves rendering optimization.
'''
[[dependencies.optileaves]]
modId = "forge"
mandatory = true
versionRange = "[47,48)"
ordering = "NONE"
side = "BOTH"
[[dependencies.optileaves]]
modId = "minecraft"
mandatory = true
versionRange = "[1.20.1]"
ordering = "NONE"
side = "BOTH"
